Bugfix for 'DSO not on commandline'
On Ubuntu Linux 22.10 the attempt to compile adrdox with ldc2 failed with:
BF71E424C08F3A6D4232856F69528B07401A46B683CB4F3FC3760DC6D5493338/adrdox.o: undefined reference to symbol 'inflateEnd'
/usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error adding symbol: DSO missing from command line

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.39

There is a workaround for this problem. See https://stackoverflow.com/questions/19901934/libpthread-so-0-error-adding-symbols-dso-missing-from-command-line

This workaround has been added and fixes the linker problem.